# title: Minimal theme
title: 冷凝-LN
logo: /assets/img/head.png
# description: Minimal is a theme for GitHub Pages.
description: Love life Love coding, change the world.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
